server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["rpa-monitor-*"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_image']
        target_label: 'image'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
        regex: '(.{12})'
    pipeline_stages:
      - json:
          expressions:
            ts: ts
            nivel: nivel
            robot: robot
            mensagem: mensagem
            run_id: run_id
      - timestamp:
          source: ts
          format: RFC3339
          fallback_formats:
            - RFC3339Nano
            - "2006-01-02T15:04:05.000Z"
      - labels:
          nivel:
          robot:
          run_id:

  # Nginx access logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>[^ ]+) - (?P<remote_user>[^ ]+) \[(?P<time_local>[^\]]+)\] "(?P<method>[^ ]+) (?P<path>[^ ]+) (?P<protocol>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
      - timestamp:
          source: time_local
          format: "02/Jan/2006:15:04:05 -0700"
      - labels:
          method:
          status:

  # Nginx error logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          level: error
          __path__: /var/log/nginx/error.log

  # Application logs from files (if needed)
  - job_name: application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: rpa-monitor
          __path__: /var/log/rpa-monitor/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: ts
            level: nivel
            message: mensagem
            robot: robot
            execution_id: run_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          robot:
          execution_id:

  # System logs (optional)
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          __path__: /var/log/syslog
