server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/log/*log

  - job_name: agent-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: agent-logs
          component: rpa-agent
          __path__: /logs/*.log

  - job_name: django-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: django-logs
          component: backend
          __path__: /app/logs/*.log

