# Generated by Django 5.2.5 on 2025-08-13 22:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('IDLE', 'Inativo'), ('RUNNING', 'Executando'), ('STOPPED', 'Parado'), ('ERROR', 'Erro'), ('MAINTENANCE', 'Manutenção')], default='IDLE', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última atividade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Robô',
                'verbose_name_plural': 'Robôs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='Nome da tarefa')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RUNNING', 'Executando'), ('COMPLETED', 'Concluída'), ('FAILED', 'Falhou'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.robot', verbose_name='Robô')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('START', 'Iniciar'), ('STOP', 'Parar'), ('RESTART', 'Reiniciar'), ('PAUSE', 'Pausar'), ('RESUME', 'Retomar'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Tipo de comando')),
                ('command_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do comando')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('ACKNOWLEDGED', 'Confirmado'), ('EXECUTED', 'Executado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Executado em')),
                ('response', models.TextField(blank=True, verbose_name='Resposta')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.robot', verbose_name='Robô')),
            ],
            options={
                'verbose_name': 'Comando',
                'verbose_name_plural': 'Comandos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Nível')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.execution', verbose_name='Execução')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.robot', verbose_name='Robô')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['robot', '-timestamp'], name='monitoring__robot_i_52f53d_idx'), models.Index(fields=['level', '-timestamp'], name='monitoring__level_a512c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='RobotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, null=True, verbose_name='Uso de CPU (%)')),
                ('memory_usage', models.FloatField(blank=True, null=True, verbose_name='Uso de memória (%)')),
                ('disk_usage', models.FloatField(blank=True, null=True, verbose_name='Uso de disco (%)')),
                ('network_status', models.BooleanField(default=True, verbose_name='Status da rede')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Dados customizados')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.robot', verbose_name='Robô')),
            ],
            options={
                'verbose_name': 'Status do Robô',
                'verbose_name_plural': 'Status dos Robôs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['robot', '-timestamp'], name='monitoring__robot_i_6c5cf6_idx')],
            },
        ),
    ]
